---
- name: Update Homebrew
  command: brew update

- name: Install Homebrew taps
  homebrew_tap:
    name: "{{ taps }}"
    state: present
  vars:
    taps:
      - heroku/brew

- name: Install command line applications using Homebrew
  homebrew:
    name: "{{ packages }}"
    state: latest
    upgrade_all: yes
  vars:
    packages:
      - ansible
      - curl
      - gcc
      - git
      - heroku
      - node
      - python3
      - redis
      - vercel-cli
      - wget
      - yarn
      - zsh

- name: Install GUI applications using Homebrew Casks for MacOS
  homebrew_cask:
    name: "{{ applications }}"
    state: latest
    upgrade_all: yes
  when: ansible_facts["distribution"] == "Darwin"
  vars:
    applications:
      - docker
      - google-backup-and-sync
      - google-chrome
      - slack
      - visual-studio-code
      - zoom

- name: Homebrew cleanup
  command: brew cleanup
