---
# Updates Homebrew to use the the latest version.
- name: Updates and upgrades Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

# Installs Homebrew taps.
- name: Install Homebrew taps
  homebrew_tap:
    name: "{{ taps }}"
    state: present
  vars:
    taps:
      - heroku/brew

# Installs latest Homebrew command line tools.
- name: Install command line applications using Homebrew
  homebrew:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ansible
      - curl
      - gcc
      - git
      - heroku
      - node
      - poetry
      - python3
      - redis
      - vercel-cli
      - wget
      - yarn

# Installs latest GUI applications for MacOS.
- name: Install GUI applications using Homebrew Casks for MacOS
  homebrew_cask:
    name: "{{ applications }}"
    state: latest
  when: ansible_facts["distribution"] == "Darwin"
  vars:
    applications:
      - docker
      - google-backup-and-sync
      - google-chrome
      - slack
      - visual-studio-code
      - zoom

# Cleans up old and cached files.
- name: Homebrew cleanup
  command: brew cleanup
